Bind Mac2Element in element map for MAC platform
appium/java-client pull request #1473
Opened 2021-05-19 17:10 UTC by DmitryMishtal

## Change list

Bind MAC platform with Mac2Element to fix ClassCastException while Mac2Driver usage
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] No changes in production code.
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2021-05-19 17:58 UTC, mykola-mokhnach commented
Thanks for fixing this
Could you please sign the CLA?

2021-05-19 20:45 UTC, valfirst requested changes

2021-05-19 20:45 UTC, valfirst commented on src/main/java/io/appium/java_client/internal/ElementMap.java
> +    MAC(MobilePlatform.MAC.toLowerCase().toLowerCase(), Mac2Element.class);
Duplicate `toLowerCase` invocation

2021-05-20 06:46 UTC, DmitryMishtal commented on src/main/java/io/appium/java_client/internal/ElementMap.java
> +    MAC(MobilePlatform.MAC.toLowerCase().toLowerCase(), Mac2Element.class);
Indeed... Seems like fixed, sry :)

2021-05-20 07:24 UTC, valfirst approved these changes

2021-05-20 08:32 UTC, DmitryMishtal commented
> Just make sure the email address of the corresponding local GH account matches to the one used to sign the CLA. The bot uses email value for comparison

Seems like i have two different emails in git config & git hub account... Should i close this PR and create a new one with correct email? Because as i understood i cant re-sign CLA for this PR with another email address

2021-05-20 15:08 UTC, closed without merging