fix: Correct spelling and semantic mistakes in method naming (#1967)
appium/java-client pull request #1970
Opened 2023-07-29 15:18 UTC by fishey2

## Change list

- corrects spelling and semantic errors
  - `SupportsCustomSslCertOption` method `setCustomSSLCert()` is now `getCustomSSLCert()` affects `XCUITestOptions`
  - `SupportsSimulatorTracePointerOption method `doesSimulatorTracePointerd()` is now `doesSimulatorTracePointer()` affects `XCUITestOption`
  - `SupportsShowChromedriverLogOption` methods `setDhowChromedriverLog(boolean)` and `doesDhowChromedriverLog()` are now `setShowChromedriverLog(boolean)` and `doesShowChromedriverLog()` respectively  affects `ExpressoOptions` and `UIAutomator2Options`

 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

No functional changes

2023-07-29 15:23 UTC, mykola-mokhnach commented
Could you please sign CLA?

2023-07-29 15:24 UTC, fishey2 commented
I should have now signed the CLA

2023-07-29 16:19 UTC, mykola-mokhnach approved these changes

2023-07-29 21:17 UTC, mykola-mokhnach commented
In order to not make this change breaking it would make sence to mark method names containing typos as `@Deprecated` and keep them for now along with corrected ones. We could remove deprecated methods  in later releases.

2023-07-30 08:33 UTC, fishey2 commented
The changes should reflect your suggestion now @mykola-mokhnach: Deprecated rather than remove methods containing typos.

2023-07-30 19:05 UTC, valfirst requested changes

2023-07-30 19:05 UTC, valfirst commented on src/main/java/io/appium/java_client/android/options/context/SupportsShowChromedriverLogOption.java
>          return amend(SHOW_CHROMEDRIVER_LOG_OPTION, value);
```suggestion
        return setShowChromedriverLog(value);
```

2023-07-30 19:05 UTC, valfirst commented on src/main/java/io/appium/java_client/android/options/context/SupportsShowChromedriverLogOption.java
>                  toSafeBoolean(getCapability(SHOW_CHROMEDRIVER_LOG_OPTION))
```suggestion
        return doesShowChromedriverLog(
```

2023-07-30 19:05 UTC, valfirst commented on src/main/java/io/appium/java_client/ios/options/simulator/SupportsCustomSslCertOption.java
>          return Optional.ofNullable((String) getCapability(CUSTOM_SSLCERT_OPTION));
```suggestion
        return getCustomSSLCert();
```

2023-07-30 19:05 UTC, valfirst commented on src/main/java/io/appium/java_client/ios/options/simulator/SupportsSimulatorTracePointerOption.java
>          return Optional.ofNullable(toSafeBoolean(getCapability(SIMULATOR_TRACE_POINTER_OPTION)));
```suggestion
        return doesSimulatorTracePointer();
```

2023-07-31 08:14 UTC, valfirst requested changes
@fishey2 would you mind fixing Checkstyle violations?

2023-07-31 08:21 UTC, fishey2 commented
@valfirst happy to work around the Checkstyle issue, however the actual checkstyle issue is apparent because it thinks the deprecated method `setCustomSSLCert()` overloads `setCustomSSLCert(String)` instead of `getCustomSSLCert()`, which should have been the case.

In this case there is only the two methods in the class and moving it up shouldn't affect anything else, but workaround the checkstyle issue. I will push this change now.

2023-07-31 09:58 UTC, valfirst approved these changes

2023-08-01 06:11 UTC, merged