Java code conventions fixes
appium/java-client pull request #2017
Opened 2023-09-17 16:01 UTC by ashwithpoojary98

## Change list

Revised method variables and parameters to meet Java code style guidelines.

2023-09-17 18:41 UTC, mykola-mokhnach commented on src/main/java/io/appium/java_client/imagecomparison/ComparisonResult.java
> +    protected ComparisonResult(Map<String, Object> commandResult) {
this is a breaking change

2023-09-17 18:43 UTC, mykola-mokhnach commented on src/main/java/io/appium/java_client/pagefactory/interceptors/InterceptorOfAListOfElements.java
> +    protected InterceptorOfAListOfElements(@Nullable ElementLocator locator) {
this is a breaking change
same below

2023-09-17 18:44 UTC, mykola-mokhnach commented on src/main/java/io/appium/java_client/remote/options/SystemScript.java
> +    protected SystemScript(Map<String, Object> options) {
same here

2023-09-17 18:45 UTC, mykola-mokhnach commented
Thank you @ashwithpoojary98 
Please rename the PR to follow https://www.conventionalcommits.org/en/v1.0.0/ 
Also please make sure you have signed the CLA

2023-09-18 06:33 UTC, ashwithpoojary98 commented on src/main/java/io/appium/java_client/imagecomparison/ComparisonResult.java
> +    protected ComparisonResult(Map<String, Object> commandResult) {
reverted the changes to public

2023-09-18 06:34 UTC, ashwithpoojary98 commented on src/main/java/io/appium/java_client/pagefactory/interceptors/InterceptorOfAListOfElements.java
> +    protected InterceptorOfAListOfElements(@Nullable ElementLocator locator) {
reverted to public

2023-09-18 06:34 UTC, ashwithpoojary98 commented on src/main/java/io/appium/java_client/remote/options/SystemScript.java
> +    protected SystemScript(Map<String, Object> options) {
reverted to public

2023-09-18 06:35 UTC, ashwithpoojary98 commented
@mykola-mokhnach updated the code as per the comment Please review

2023-09-18 11:16 UTC, mykola-mokhnach commented on src/main/java/io/appium/java_client/remote/options/SystemScript.java
> +    protected SystemScript() {
this is a breaking change

2023-09-18 11:33 UTC, ashwithpoojary98 commented on src/main/java/io/appium/java_client/remote/options/SystemScript.java
> +    protected SystemScript() {
reverted the changes

2023-09-18 12:21 UTC, ashwithpoojary98 commented
updated the workflow issue

2023-09-19 15:19 UTC, ashwithpoojary98 commented
Updated workflow issue

2023-09-20 07:24 UTC, valfirst requested changes

2023-09-20 07:24 UTC, valfirst commented on src/main/java/io/appium/java_client/pagefactory/bys/builder/AppiumByBuilder.java
> + * - <a href="https://code.google.com/p/selenium/wiki/PageFactory">https://code.google.com/p/selenium/wiki/PageFactory</a>
```suggestion
 * - <a href="https://github.com/SeleniumHQ/selenium/wiki/PageFactory">Selenium Page Factory</a>
```

2023-09-20 07:24 UTC, valfirst commented on src/main/java/io/appium/java_client/pagefactory/bys/builder/AppiumByBuilder.java
> + * - <a href="https://code.google.com/p/selenium/wiki/PageObjects">https://code.google.com/p/selenium/wiki/PageObjects</a>
```suggestion
 * - <a href="https://www.selenium.dev/documentation/test_practices/encouraged/page_object_models/">Selenium Page Object models</a>
```

2023-09-20 14:03 UTC, SrinivasanTarget approved these changes

2023-09-21 08:47 UTC, valfirst approved these changes

2023-09-23 06:01 UTC, ashwithpoojary98 commented
All checks have passed!!

2023-09-23 18:01 UTC, merged